from lumicks.pylake.kymo import Kymo
from lumicks.pylake.scan import Scan
from lumicks.pylake.channel import empty_slice
from lumicks.pylake.point_scan import PointScan
from lumicks.pylake.detail.confocal import ConfocalFile, ScanMetaData


def create_confocal_object(
    name,
    infowave,
    json_metadata,
    red_channel=empty_slice,
    green_channel=empty_slice,
    blue_channel=empty_slice,
) -> Kymo | Scan:
    """Create a confocal object from slices and json metadata

    Parameters
    ----------
    name : str
        Name of this object
    infowave : lumicks.pylake.Slice
        Info wave that encodes how the photon counts should be assembled into an image.
    red_channel, green_channel, blue_channel : lumicks.pylake.Slice
        Photon counts
    json_metadata : str
        json metadata generated by Bluelake.
    """
    metadata = ScanMetaData.from_json(json_metadata)
    file = ConfocalFile(infowave, red_channel, green_channel, blue_channel)
    confocal_cls = {0: PointScan, 1: Kymo, 2: Scan}
    return confocal_cls[metadata.num_axes](name, file, infowave.start, infowave.stop, metadata)
