from lumicks.pylake.kymo import Kymo
from lumicks.pylake.scan import Scan
from lumicks.pylake.detail.confocal import ConfocalFile, ScanMetaData


def create_confocal_object(
    name, infowave, red_channel, green_channel, blue_channel, json_metadata
) -> Kymo | Scan:
    """Create a confocal object from slices and json metadata

    Parameters
    ----------
    name : str
        Name of this object
    infowave : lumicks.pylake.Slice
        Info wave that encodes how the photon counts should be assembled into an image.
    red_channel, green_channel, blue_channel : lumicks.pylake.Slice
        Photon counts
    json_metadata : str
        Json metadata generated by Bluelake.
    """
    metadata = ScanMetaData.from_json(json_metadata)
    file = ConfocalFile(infowave, red_channel, green_channel, blue_channel)

    for ch in (red_channel, green_channel, blue_channel):
        assert ch.start == infowave.start

    confocal_cls = Kymo if metadata.num_axes == 1 else Scan
    return confocal_cls(name, file, infowave.start, infowave.stop, metadata)
