repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
    exclude: ^.*\.png$ ^.*\.gif$
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    exclude: ^.*\.png$ ^.*\.gif$
- repo: https://github.com/pycqa/flake8
  rev: 7.1.0
  hooks:
  - id: flake8
    language_version: python3
    additional_dependencies:
      - flake8-bugbear==24.4.26
