name: deploy

on:
  push:
    tags:
      - v*

env:
  JUPYTER_PLATFORM_DIRS: "1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools build wheel twine
    - name: Build and check package
      run: |
        python -m build
        python -m twine check --strict dist/*
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
