name: pytest

on: [push]

env:
  # See: https://github.com/jupyter/jupyter_core/pull/292#issuecomment-1258284246
  JUPYTER_PLATFORM_DIRS: "1"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[notebook]
    - name: Pytest
      run: |
        cd .github/workflows
        python pylake_test.py
    - name: Benchmark
      run: python -c "import lumicks.pylake as lk; lk.benchmark(repeat=1)"
    - name: Black
      run: |
        pip install black==23.7.0 isort==5.12.0
        black --check --diff --color .
        isort --check-only --diff .
    - name: flake8
      run: |
        pip install flake8 flake8-bugbear
        flake8 .
