name: docs build

on: [push]

env:
  JUPYTER_PLATFORM_DIRS: "1"

jobs:
    build_docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            lfs: true
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
              python-version: '3.10'
              cache: 'pip'
              cache-dependency-path: pyproject.toml
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .
            pip install -r docs/requirements.txt
        - name: Build the docs
          run: |
            python -m sphinx -W -b html docs build/html
