name: coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov
        pip install .
    - name: Generate coverage report
      run: |
        pytest --cov=./ --cov-report=xml
        pytest --cov=./cov_html/ --cov-report=html
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    - name: Upload coverage to GH artefacts
    - uses: actions/upload-artifact@v2
      with:
        name: test-artifact
        path: ./cov_html/